apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: weaviate-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weaviate
  minReplicas: 1 # Minimum number of pods to maintain
  maxReplicas: 5 # Maximum number of pods to scale up to
  metrics:
    - type: Resource
      resource:
        name: cpu # Type of metric to scale on (CPU)
        target:
          type: Utilization
          averageUtilization: 70 # Target average CPU utilization percentage
    - type: Resource
      resource:
        name: memory # Type of metric to scale on (Memory)
        target:
          type: Utilization
          averageUtilization: 70 # Target average Memory utilization percentage
